version: 2
updates:
  - package-ecosystem: maven
    directory: /java
    schedule:
      interval: weekly
  # The root package.json currently has no npm dependencies.
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
