sonar.organization=dflippojr
sonar.projectKey=dflippojr_integration-failure-lab
sonar.projectName=integration-failure-lab
sonar.sourceEncoding=UTF-8
sonar.sources=engine,ui,scripts,java/src/main/java
sonar.tests=test,java/src/test/java
sonar.java.binaries=java/target/classes
sonar.java.test.binaries=java/target/test-classes
sonar.javascript.lcov.reportPaths=lcov.info
sonar.coverage.jacoco.xmlReportPaths=java/target/site/jacoco/jacoco.xml
