// Assemble dist/ for embedding: engine.js, lab.js, lab.css, and scenarios.js generated from scenarios/*.json.
// Usage: node scripts/build.mjs [dist|site|test]   (default: dist)
//   dist  this repo's dist/
//   site  ../personal-website/public/lab, the website checkout next to this repo
//   test  dist-test/ (git-ignored), the generated modules the UI tests import
// Targets are fixed names, never paths, so the build cannot be pointed anywhere else.
import { readdirSync, readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
let out;
switch (process.argv[2] ?? 'dist') {
  case 'dist': out = join(root, 'dist'); break;
  case 'site': out = join(root, '..', 'personal-website', 'public', 'lab'); break;
  case 'test': out = join(root, 'dist-test'); break;
  default:
    console.error(`Unknown target "${process.argv[2]}"; use dist, site or test.`);
    process.exit(1);
}
mkdirSync(out, { recursive: true });

const scenarios = readdirSync(join(root, 'scenarios'))
  .filter(f => f.endsWith('.json'))
  .map(f => JSON.parse(readFileSync(join(root, 'scenarios', f), 'utf8')))
  .sort((a, b) => a.order - b.order);

const execDir = join(root, 'executed');
const executed = {};
for (const f of readdirSync(execDir).filter(f => f.endsWith('.json') && f !== 'index.json')) {
  const x = JSON.parse(readFileSync(join(execDir, f), 'utf8'));
  const { scenarioId, generatedAt, runtime, timing, trace, record, dlq, dropped, buffered } = x;
  executed[scenarioId] = { generatedAt, runtime, timing, trace, record, dlq, dropped, buffered };
}
writeFileSync(join(out, 'scenarios.js'),
  `// Generated by scripts/build.mjs from scenarios/*.json and executed/*.json IDs. Do not edit.\nexport const SCENARIOS = ${JSON.stringify(scenarios, null, 2)};\nexport const RECORDING_IDS = ${JSON.stringify(Object.keys(executed))};\n`);
writeFileSync(join(out, 'executed.js'),
  `// Generated by scripts/build.mjs from executed/*.json (recorded by the Java/Spring runner). Do not edit.
export const EXECUTED = ${JSON.stringify(executed)};
`);
copyFileSync(join(root, 'engine', 'engine.js'), join(out, 'engine.js'));
copyFileSync(join(root, 'ui', 'lab.js'), join(out, 'lab.js'));
copyFileSync(join(root, 'ui', 'lab.css'), join(out, 'lab.css'));
console.log(`Built ${scenarios.length} scenarios and ${Object.keys(executed).length} executed traces into ${out}`);
