// Assemble dist/ for embedding: engine.js, lab.js, lab.css, and scenarios.js generated from scenarios/*.json.
// Usage: node scripts/build.mjs [targetDir]   (default: dist). The website vendors this into public/lab/.
import { readdirSync, readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const out = resolve(process.argv[2] ?? join(root, 'dist'));
mkdirSync(out, { recursive: true });

const scenarios = readdirSync(join(root, 'scenarios'))
  .filter(f => f.endsWith('.json'))
  .map(f => JSON.parse(readFileSync(join(root, 'scenarios', f), 'utf8')))
  .sort((a, b) => a.order - b.order);

writeFileSync(join(out, 'scenarios.js'),
  `// Generated by scripts/build.mjs from scenarios/*.json. Do not edit.\nexport const SCENARIOS = ${JSON.stringify(scenarios, null, 2)};\n`);
const execDir = join(root, 'executed');
const executed = {};
for (const f of readdirSync(execDir).filter(f => f.endsWith('.json') && f !== 'index.json')) {
  const x = JSON.parse(readFileSync(join(execDir, f), 'utf8'));
  const { scenarioId, generatedAt, runtime, timing, trace, record, dlq, dropped, buffered } = x;
  executed[scenarioId] = { generatedAt, runtime, timing, trace, record, dlq, dropped, buffered };
}
writeFileSync(join(out, 'executed.js'),
  `// Generated by scripts/build.mjs from executed/*.json (recorded by the Java/Spring runner). Do not edit.
export const EXECUTED = ${JSON.stringify(executed)};
`);
copyFileSync(join(root, 'engine', 'engine.js'), join(out, 'engine.js'));
copyFileSync(join(root, 'ui', 'lab.js'), join(out, 'lab.js'));
copyFileSync(join(root, 'ui', 'lab.css'), join(out, 'lab.css'));
console.log(`Built ${scenarios.length} scenarios and ${Object.keys(executed).length} executed traces into ${out}`);
